### ISSUE TITLE
The two lists of bookmarks should have the same functionality

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#1]
The list of bookmarks on a team's home page is not the same as the list on the digest builder page:

### Team home
![Image](https://user-images.githubusercontent.com/1102595/266605175-77c02055-82ec-42ca-8faf-8f861c78abf8.png)

vs

### Digest builder
![Image](https://user-images.githubusercontent.com/1102595/266605208-6ac69ffa-94b4-42c0-b376-2e6f4e3d9c11.png)

The two lists should be harmonised to ensure the same look and feel: 

 - Search on both lists
 - Bookmark description on both lists
 - Deletion on both lists

**Comment by Lucieo** [comment]
- [ ] Add search on Team bookmarks list
- [ ] Add description on Team bookmarks list
- [ ] Enable deletion of a bookmark in digest create page
