### ISSUE TITLE
Change the color + location of the "add bookmark" button

### ISSUE THREAD

**Issue by anthonymaison** [premieroctet/digestclub#118]
The current "add bookmark" button is the only green component, and its location makes it difficult to see at first use. Here's a suggestion:
![CleanShot 2024-04-24 at 20 18 37@2x](https://github.com/premieroctet/digestclub/assets/6388444/dc9a07fd-1bf1-46b1-a86c-d33f56d9612c)

**Comment by quentingrchr** [comment]
Good idea 🚀
I think we can keep the button in the header, but we'll add another one close to the search bar like you're suggesting.
Also it could be nice to add a shortcut to open this "Add bookmark" modal (Ctrl + B ?)
