### ISSUE TITLE
Upgrade React / TS types to support async component

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#13]
We need to upgrade React / TS types to avoid async component TS errors (`Promise<Element> is not a valid JSX element type` error)

**Comment by shinework** [comment]
Related to https://github.com/premieroctet/digestclub/issues/13

**Comment by Lucieo** [comment]
For now it's conflicting with React beautiful dnd lib

**Comment by quentingrchr** [comment]
Looks like we can use [async components now](https://github.com/premieroctet/digestclub/blob/5434afe00274d250b2a266f7a86187f9812a03b9/src/components/charts/ChartsServer.tsx#L33)
