### ISSUE TITLE
Missing pagination at the bottom of bookmark list, missing padding

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#2]
On the digest builder bookmark list, the pagination module is only on the top, we can add the module on the bottom of the list too : 

![image](https://github.com/premieroctet/digestclub/assets/1102595/58f8cce3-e555-4ce1-9a76-4eed20bf9f2c)

Same on the team home list : 

![image](https://github.com/premieroctet/digestclub/assets/1102595/503a3da6-3422-40c2-b45a-1eb36d44c267)

A little bottom margin is also missing under the digest builder list : 

![image](https://github.com/premieroctet/digestclub/assets/1102595/4f73916c-45f4-474d-98a5-0b664ca88b5b)

**Comment by Lucieo** [comment]
- [ ] Add pagination bottom Team bookmarks list
- [ ] Add pagination bottom Digest Edition bookmarks list
- [ ] Add padding bottom Team page
