### ISSUE TITLE
Predict the name of the next digest

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#22]
Fun feature  use openai w/ gpt to predict the next digest name. We need to craft the prompt with something like:

```
Here is a list of document titles sorted from oldest to most recent: 

// inject digest titles, ie:
Tech paf #1
Tech paf #2
Tech paf #3

Give the next document title (only the title, without another word):
```

Example of code : https://github.com/shinework/photoshot/blob/0dc7e8b51229670d5a702383f029c402de99675c/src/pages/api/projects/%5Bid%5D/prompter.ts#L25

or maybe we can use: https://sdk.vercel.ai/docs/guides/providers/openai

we can add a small label/link to generate the title below the input: 

![image](https://github.com/premieroctet/digestclub/assets/1102595/16d76af1-70cf-4607-9838-018d97c716e0)

**Comment by MrNossiom** [comment]
Maybe this could be done simply with pattern matching on `#n` and print `#(n+1)`.
Other numbering format could be implemented.
