### ISSUE TITLE
Public Digest page always displays 10 bookmarks

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#28]
The bookmarks badge on the public digest page always displays 10 bookmarks:

<img width="997" alt="image" src="https://github.com/premieroctet/digestclub/assets/1102595/7c0e22b2-6e5f-4abf-b9b9-f44ea802e5ed">

<img width="957" alt="image" src="https://github.com/premieroctet/digestclub/assets/1102595/4b65dcf6-d192-4dfd-b76e-3c4ff9e04159">

**Comment by Lucieo** [comment]
This is due to the fact that Text Blocks are accounted as Bookmarks
