### ISSUE TITLE
Insert a block should be highlighted directly in the list

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#3]
The location of the button to add a markdown in a digest is not obvious : 

![image](https://github.com/premieroctet/digestclub/assets/1102595/5204988e-c43d-4f97-be7d-b304a1dd4546)

It should be great if we can add a little circle button with "+" label between two bookmark cards to add this block : 

![image](https://github.com/premieroctet/digestclub/assets/1102595/e515479a-ff94-43ba-8961-3b8b5a458d46)

**Comment by Lucieo** [comment]
![Image](https://github.com/premieroctet/digestclub/assets/25606391/cc06b122-e20f-482c-a273-ead7267ed6ba)
