### ISSUE TITLE
Improve "all bookmarks" button

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#4]
By default, bookmarks in a digest are not displayed. User can use the "All bookmark button" to display them: 

![image](https://github.com/premieroctet/digestclub/assets/1102595/358d6a26-9669-474e-9a72-65f85256762e)

However, this button isn't very clear; we should use a switch button instead with the label "View all bookmarks".

There is another issue : 
- when an user clicks on the button, the page query should be removed to avoid weird state pagination

**Comment by Lucieo** [comment]
- [ ] Use switch and change wording for all bookmarks button
- [ ] Reset page number on switch

**Comment by Lucieo** [comment]
- [ ] Fix DarkMode
