### ISSUE TITLE
Highlight trending bookmark

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#7]
When a same bookmark has been added many times in a same team, we should display an indicator (badge? bg color?) in the card to spot it

![image](https://github.com/premieroctet/digestclub/assets/1102595/a1fdd29e-7922-4c98-b95b-5de9c9e8b30f)

**Comment by Lucieo** [comment]
Note quite sure about how we should do here, should we change prisma model to replace Membership/Bookmark one to one to a one-to-many relation  ?

**Comment by Lucieo** [comment]
- Keep unity of each bookmark
- Just display a counter on each bookmark if link is already share in team
