### ISSUE TITLE
Make the digest builder sticky

### ISSUE THREAD

**Issue by shinework** [premieroctet/digestclub#72]
Make the right digest builder sticky on scroll : 

https://github.com/premieroctet/digestclub/assets/1102595/f2c169d1-4631-4424-a62f-4e3adfcb4756

**Comment by quentingrchr** [comment]
@shinework But what would happen in this case ? when the builder is longer than the bookmarks list ? 

![image](https://github.com/premieroctet/digestclub/assets/51860690/bcb6085d-7fb4-464c-b8d4-3b351486984e)

**Comment by shinework** [comment]
we can also stick it in this case
