### ISSUE TITLE
Deleting a team is logging me out and removing me from all team

### ISSUE THREAD

**Issue by tlenclos** [premieroctet/digestclub#80]
I had 2 teams, I removed the second one and got logged out and removed from all teams.

It probably removed my account completely.

**Comment by quentingrchr** [comment]
I tried:

with an account (USER) having `USER` membership on Team A and Team B, I deleted Team B
with an account (SUPERADMIN) having `ADMIN` membership on Team A and Team B, I deleted Team B
Not reproduced

**Comment by tlenclos** [comment]
I might have been too fast and removed my account instead of the team.
