### ISSUE TITLE
Enhancement proposal : Topics / Tags for a digest

### ISSUE THREAD

**Issue by quentingrchr** [premieroctet/digestclub#84]
# 🏷️ Topics/Tags for Digests

## Enhance discoverability with tags for digests

**Issue Description**
Currently, the discover page lacks a filtering feature, making it challenging for users to find digests related to specific topics like _design_ or _tech_.

**Desired Solution**
Adding the functionality for digest creators to assign topics or tags to their digests. This way, users can easily filter and discover digests based on their interests. An example of this can be seen in the [dev.to](https://dev.to/) platform.

**Visual Representation**

- Discover Page:

  ![Discover Page](https://github.com/premieroctet/digestclub/assets/51860690/121c4077-b33f-42c1-8c1f-1acb41eb5b70)

- Example: #WebDev Topic

  ![WebDev Topic](https://github.com/premieroctet/digestclub/assets/51860690/feca2451-7196-4112-a6c6-3fdb07ce91fd)

**Comment by tlenclos** [comment]
Ca serait une chouette amélio effectivement.

J'imagine qu'on pourrait extraire des tags pour un digest via le contenu de chaque lien. Il faudrait ensuite les normalizer (ie "React.js" VS "React"), et les sauver en base.
On pourrait ensuite afficher les tags les plus utilisées dans la barre à droite de la page https://digest.club/discover
